# Lunar Anticheat Configure File
CPSTag: true
ClientDataFaker:
  Enable: true
  Punishment: BAN
  DeviceOS:
    - 1
    - 2
    - 7
  DeviceModel:
    - "EZ4H"
    - "VMOS"
NukerA:
  Enable: true
  Punishment: KICK
  # Max Block Breaks in 20ms
  MaxBlock: 3
AutoClicker:
  Enable: true
  Punishment: KICK
  # Max CPS
  MaxCPS: 35