# Lunar Anticheat Configure File
Prefix: "§7[§fLunar§7]"
Replace: true
CPSTag: true
# Punishment(BAN, KICK, ALERT, IGNORE)
ClientDataFaker:
  Enable: true
  Punishment: BAN
  DeviceOS:
    - 1
    - 2
    - 7
  DeviceModel:
    - "EZ4H"
    - "VMOS"
# Action
NukerA:
  Enable: true
  Punishment: KICK
  # Max Block Breaks in 20ms
  MaxBlock: 3
  MaxVL: 5
FastBreakA:
  Enable: true
  Punishment: KICK
  MaxVL: 5
AutoClicker:
  Enable: true
  Punishment: BAN
  # Max CPS
  MaxCPS: 25
  MaxVL: 5
  Reward: 0.988
# Combat
KillAuraA:
  Enable: false
  MaxVL: 10
  Punishment: KICK
  AttackCooldown: 3
  Radius: 3
  Random:
    Y:
      Min: -1
      Max: 3
KillAuraB:
  Enable: true
  Punishment: KICK
  MaxVL: 5
  SwingDuration: 0.35
MultiAura:
  Enable: true
  Punishment: BAN
  MaxVL: 5
  MaxEntityHit: 4
ReachA:
  Enable: true
  Punishment: KICK
  MaxVL: 5

# Movement
#  Speed
SpeedA:
  Enable: true
  Punishment: KICK
  Suppress: true
  MaxVL: 10
  Diff: 0.000000000001
  Reward: 0.888
SpeedC:
  Enable: true
  Punishment: KICK
  Suppress: true
  MaxVL: 10
  Diff: 0.000000000001
  Reward: 0.1
#  Fly
FlyA:
  Enable: false
  Punishment: KICK
  Suppress: true
  MaxVL: 40
  Diff: 0.001
  Reward: 0.888
FlyB:
  Enable: true
  Punishment: KICK
  Suppress: true
  MaxVL: 10
  Reward: 0.85
FlyE:
  Enable: true
  Punishment: KICK
  Suppress: true
  MaxVL: 40
  Reward: 0.88
  Diff: 0.01

MotionA:
  Enable: false
  Punishment: KICK
  MaxVL: 10
# Network
BadPacketA:
  Enable: true
  Punishment: BAN
  MaxVL: 5