# Lunar Anticheat Configure File
Prefix: "§7[§fLunar§7]"
CPSTag: true
# Punishment(BAN, KICK, ALERT, IGNORE)
ClientDataFaker:
  Enable: true
  Punishment: BAN
  DeviceOS:
    - 1
    - 2
    - 7
  DeviceModel:
    - "EZ4H"
    - "VMOS"
# Action
NukerA:
  Enable: true
  Punishment: KICK
  # Max Block Breaks in 20ms
  MaxBlock: 3
  MaxVL: 10
  Reward: 0.988
AutoClicker:
  Enable: true
  Punishment: KICK
  # Max CPS
  MaxCPS: 35
  MaxVL: 10
  Reward: 0.988
# Combat
KillAura:
  Enable: false
  MaxVL: 10
  Punishment: KICK
  AttackCooldown: 3
  Radius: 3
  Random:
    Y:
      Min: -1
      Max: 3
MultiAura:
  Enable: true
  Punishment: KICK
  MaxVL: 10
  MaxEntityHit: 5

# Movement
SpeedA:
  Enable: true
  Punishment: KICK
  MaxVL: 10
  Diff: 0.000000000001
  Reward: 0.888
SpeedC:
  Enable: true
  Punishment: KICK
  MaxVL: 10
  Diff: 0.000000000001
  Reward: 0.1
FlyA:
  Enable: true
  Punishment: KICK
  MaxVL: 10
  Diff: 0.001
  Reward: 0.666
FlyB:
  Enable: true
  Punishment: KICK
  MaxVL: 10
  Reward: 0.85
FlyD:
  Enable: false
  Punishment: KICK
  MaxVL: 10
  Reward: 0.99

# Network
BadPacketA:
  Enable: true
  Punishment: KICK
  MaxVL: 5