# Lunar Anticheat Configure File
# Alert Message Prefix
Prefix: "§7[§fLunar§7]"
# Alert Message format (with prefix)
#  Available Variable [MSG, DETECTION_NAME, PLAYER_NAME, MAX_VL, VL, PRE_VL, PUNISHMENT, PUNISHMENT_STRING]
Format: "[DETECTION_NAME]: [MSG]"
# Replace Config file by default
Replace: true
# In-Game CPS TAG
CPSTag: true
# Punishment(BAN, KICK, ALERT, IGNORE)

# Check for wrong edition provided and DeviceModel
ClientDataFaker:
  Enable: true
  Punishment: BAN
  DeviceOS:
    - 1
    - 2
    - 7
  DeviceModel:
    - "EZ4H"


# Action

# break too many block in 20ms
NukerA:
  Enable: true
  Punishment: BAN
  MaxVL: 5
  # Max Block Breaks in 20ms
  MaxBlock: 3

# Break block faster than prediction
FastBreakA:
  Enable: true
  Punishment: ALERT
  MaxVL: 5

# Basic high CPS with a certain limit
AutoClicker:
  Enable: true
  Punishment: BAN
  MaxVL: 5
  # Max CPS
  MaxCPS: 25
  Reward: 0.988


# Combat

# Check for slapper hit
KillAuraA:
  Enable: false
  MaxVL: 5
  Punishment: KICK
  AttackCooldown: 3
  Radius: 3
  Random:
    Y:
      Min: -1
      Max: 3

# Check for attack without swing arm
KillAuraB:
  Enable: true
  Punishment: KICK
  MaxVL: 5
  SwingDuration: 0.3

# Check for attack multiple entity with impossible count
MultiAura:
  Enable: true
  Punishment: BAN
  MaxVL: 5
  MaxEntityHit: 4

# Basic attack distance check
ReachA:
  Enable: false
  Punishment: ALERT
  MaxVL: 5

# Check for vertical velocity
VelocityB:
  Enable: true
  Punishment: ALERT
  MaxVL: 5


# Movement

# Checks for horizontal friction
SpeedA:
  Enable: false
  Punishment: KICK
  MaxVL: 5
  Suppress: false
  MaxDiff: 0.000000000001
  Reward: 0.888

# Basic verbose speed check
SpeedC:
  Enable: true
  Punishment: KICK
  MaxVL: 5
  Suppress: false
  Reward: 0.1


# Check for flight's that don't obey gravity.
FlyA:
  Enable: true
  Punishment: KICK
  MaxVL: 5
  Suppress: false
  Reward: 0.888

# Basic AirJump check
FlyB:
  Enable: true
  Punishment: KICK
  MaxVL: 5
  Suppress: false
  Reward: 0.85

# Checks for small vertical movement.
FlyE:
  Enable: true
  Punishment: KICK
  MaxVL: 5
  Suppress: false
  MaxDiff: 0.01
  Reward: 0.88

# Check for invalid horizontal acceleration. Like BHop, Speed
MotionA:
  Enable: true
  Punishment: KICK
  MaxVL: 5

#  Check for invalid vertical acceleration. Like HighJump
MotionB:
  Enable: true
  Punishment: KICK
  MaxVL: 5


# Network

#  Check for invalid self hit action
BadPacketA:
  Enable: true
  Punishment: BAN
  MaxVL: 5